/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_projekat1_FahrConverter */

#ifndef _Included_com_example_projekat1_FahrConverter
#define _Included_com_example_projekat1_FahrConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_projekat1_FahrConverter
 * Method:    CelsiusToFahrenheit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_projekat1_FahrConverter_CelsiusToFahrenheit
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_example_projekat1_FahrConverter_FahrenheitToCelsius
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
